<?php require __DIR__.'/bootstrap.php';
if($_SERVER['REQUEST_METHOD']!=='POST') json(['error'=>'method'],405);
$data=json_decode(file_get_contents('php://input'),true)?:$_POST;
$email=trim(strtolower($data['email']??'')); $pass=$data['password']??'';
if(!$email||!$pass) json(['error'=>'missing'],400);
$pdo=get_db(); $stmt=$pdo->prepare("SELECT * FROM users WHERE email=?"); $stmt->execute([$email]); $u=$stmt->fetch();
if(!$u||!password_verify($pass,$u['password_hash'])) json(['error'=>'invalid'],401);
if($u['status']!=='active') json(['error'=>'not_active','status'=>$u['status']],403);
$_SESSION['user']=['id'=>$u['id'],'email'=>$u['email'],'name'=>$u['name'],'role'=>$u['role'],'status'=>$u['status'],'business_name'=>$u['business_name']??''];
json(['ok'=>true,'user'=>$_SESSION['user'],'csrf'=>$_SESSION['csrf']]);
